version: '3'

volumes:
  postgres_data:
  ipython_data:

services:
  postgres:
    image: drug-store-postgres
    build: ./compose/postgres
    container_name: drug-store-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  django:
    image: drug-store-django
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: drug-store-django
    command: /gunicorn.sh
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.settings_prod
    env_file:
      - .env
    volumes:
      - .:/app
      - ipython_data:/root/.ipython
    ports:
      - "8000:8000"
    links:
      - postgres
