# Generated by Django 3.0.4 on 2020-06-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20200619_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
