# Generated by Django 3.1.2 on 2020-10-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20201024_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.workspace'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.workspace'),
        ),
    ]
