# Generated by Django 3.0.4 on 2020-06-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_prescription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
