# Generated by Django 3.0.4 on 2020-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_auto_20200622_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='condition',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=11),
        ),
    ]
