# Generated by Django 3.0.4 on 2020-08-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0005_auto_20200701_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
