# Generated by Django 3.0.4 on 2020-08-12 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0006_drug_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyPrescription',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Prescription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
