# Generated by Django 3.0.4 on 2020-08-14 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0007_pharmacyprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='total_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
