# Generated by Django 3.0.4 on 2020-08-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0008_prescription_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyPrescription',
        ),
    ]
