# Generated by Django 3.0.4 on 2020-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0009_delete_pharmacyprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetail',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
