# Generated by Django 3.0.4 on 2020-09-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0010_prescriptiondetail_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
