# Generated by Django 3.0.4 on 2020-09-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0011_pharmacy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiondetail',
            name='is_available',
        ),
    ]
