# Generated by Django 3.0.4 on 2020-10-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0012_remove_prescriptiondetail_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptiondetail',
            unique_together={('prescription', 'drug')},
        ),
    ]
